"""empty message

Revision ID: b4e39389c886
Revises: 
Create Date: 2026-08-28 23:29:16.704242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e39389c886'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('user')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('click', sa.Integer(), nullable=True))
        op.execute("UPDATE post SET delete_token = 'legacy-token' WHERE delete_token IS NULL")
        batch_op.alter_column('delete_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('delete_token',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('click')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('favorites_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favorites_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('favorites_pkey'))
    )
    # ### end Alembic commands ###
